// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Models;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(CnpmContext))]
    [Migration("20260311112850_update Hottels Tour Tourist_Area Img Review Favorite")]
    partial class updateHottelsTourTourist_AreaImgReviewFavorite
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("favorites_pkey");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_favorites_user_id");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_favorites_entity");

                    b.HasIndex("UserId", "EntityType", "EntityId")
                        .HasDatabaseName("ix_favorites_user_entity");

                    b.ToTable("favorites", (string)null);
                });

            modelBuilder.Entity("backend.Models.Hottel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<int>("ClickCount")
                        .HasColumnType("integer")
                        .HasColumnName("click_count");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_on")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("Created_By_UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("FavoriteCount")
                        .HasColumnType("integer")
                        .HasColumnName("favorite_count");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("NumberOfPeople")
                        .HasColumnType("integer")
                        .HasColumnName("number_of_people");

                    b.Property<decimal>("RatingAverage")
                        .HasColumnType("numeric")
                        .HasColumnName("rating_average");

                    b.Property<int>("RatingCount")
                        .HasColumnType("integer")
                        .HasColumnName("rating_count");

                    b.Property<int>("RatingTotal")
                        .HasColumnType("integer")
                        .HasColumnName("rating_total");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int>("Tourist_Area_Id")
                        .HasColumnType("integer")
                        .HasColumnName("tourist_area_id");

                    b.HasKey("Id")
                        .HasName("hottels_pkey");

                    b.HasIndex("ClickCount")
                        .HasDatabaseName("ix_hottels_click");

                    b.HasIndex("CreatedOn")
                        .HasDatabaseName("ix_hottels_created_on");

                    b.HasIndex("Created_By_UserId")
                        .HasDatabaseName("ix_hottels_created_by_user");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_hottels_name");

                    b.HasIndex("RatingAverage")
                        .HasDatabaseName("ix_hottels_rating");

                    b.HasIndex("Tourist_Area_Id")
                        .HasDatabaseName("ix_hottels_tourist_area_id");

                    b.HasIndex("RatingAverage", "ClickCount")
                        .HasDatabaseName("ix_hottels_popular");

                    b.ToTable("hottels", (string)null);
                });

            modelBuilder.Entity("backend.Models.Img", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_type");

                    b.Property<bool>("IsCover")
                        .HasColumnType("boolean")
                        .HasColumnName("is_cover");

                    b.Property<string>("url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("imgs_pkey");

                    b.HasIndex("IsCover")
                        .HasDatabaseName("ix_imgs_cover");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_imgs_entity");

                    b.ToTable("imgs", (string)null);
                });

            modelBuilder.Entity("backend.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_revoked");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("refresh_tokens_pkey");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_refresh_tokens_expires_at");

                    b.HasIndex("TokenHash")
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("backend.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_type");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("reviews_pkey");

                    b.HasIndex("Score")
                        .HasDatabaseName("ix_reviews_score");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_reviews_user_id");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_reviews_entity");

                    b.ToTable("reviews", (string)null);
                });

            modelBuilder.Entity("backend.Models.Tour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<int>("ClickCount")
                        .HasColumnType("integer")
                        .HasColumnName("click_count");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("Created_By_UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("DurationDays")
                        .HasColumnType("integer")
                        .HasColumnName("duration_days");

                    b.Property<int>("FavoriteCount")
                        .HasColumnType("integer")
                        .HasColumnName("favorite_count");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("NumberOfPeople")
                        .HasColumnType("integer")
                        .HasColumnName("number_of_people");

                    b.Property<decimal>("RatingAverage")
                        .HasColumnType("numeric")
                        .HasColumnName("rating_average");

                    b.Property<int>("RatingCount")
                        .HasColumnType("integer")
                        .HasColumnName("rating_count");

                    b.Property<int>("RatingTotal")
                        .HasColumnType("integer")
                        .HasColumnName("rating_total");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int?>("Tourist_AreaId")
                        .HasColumnType("integer");

                    b.Property<int>("Tourist_Area_Id")
                        .HasColumnType("integer")
                        .HasColumnName("tourist_area_id");

                    b.HasKey("Id")
                        .HasName("tour_id");

                    b.HasIndex("ClickCount")
                        .HasDatabaseName("ix_tours_click");

                    b.HasIndex("CreatedOn")
                        .HasDatabaseName("ix_tours_created_on");

                    b.HasIndex("Created_By_UserId")
                        .HasDatabaseName("ix_tours_created_by_user");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_tours_name");

                    b.HasIndex("RatingAverage")
                        .HasDatabaseName("ix_tours_rating");

                    b.HasIndex("Tourist_AreaId");

                    b.HasIndex("Tourist_Area_Id")
                        .HasDatabaseName("ix_tours_tourist_area_id");

                    b.HasIndex("RatingAverage", "ClickCount")
                        .HasDatabaseName("ix_tours_popular");

                    b.ToTable("Tours", (string)null);
                });

            modelBuilder.Entity("backend.Models.Tourist_Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<int>("ClickCount")
                        .HasColumnType("integer")
                        .HasColumnName("click_count");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_on")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("Created_By_UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("FavoriteCount")
                        .HasColumnType("integer")
                        .HasColumnName("favorite_count");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal>("RatingAverage")
                        .HasColumnType("numeric")
                        .HasColumnName("rating_average");

                    b.Property<int>("RatingCount")
                        .HasColumnType("integer")
                        .HasColumnName("rating_count");

                    b.Property<int>("RatingTotal")
                        .HasColumnType("integer")
                        .HasColumnName("rating_total");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("tourist_areas_pkey");

                    b.HasIndex("ClickCount")
                        .HasDatabaseName("ix_tourist_area_click");

                    b.HasIndex("CreatedOn")
                        .HasDatabaseName("ix_tourist_area_created_on");

                    b.HasIndex("Created_By_UserId")
                        .HasDatabaseName("ix_tourist_areas_created_by_user");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_tourist_areas_name");

                    b.HasIndex("RatingAverage")
                        .HasDatabaseName("ix_tourist_area_rating");

                    b.HasIndex("RatingAverage", "ClickCount")
                        .HasDatabaseName("ix_tourist_area_popular");

                    b.ToTable("tourist_areas", (string)null);
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Avt")
                        .HasColumnType("text")
                        .HasColumnName("avt");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<DateTime?>("ResetPasswordExpiry")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("ResetPasswordExpiry")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ResetPasswordToken")
                        .HasColumnType("text")
                        .HasColumnName("ResetPasswordToken");

                    b.Property<string>("Role")
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("User_Search_History")
                        .HasColumnType("text")
                        .HasColumnName("User_Search_History");

                    b.HasKey("Id")
                        .HasName("users_pkey");

                    b.HasIndex("Role")
                        .HasDatabaseName("ix_users_role");

                    b.HasIndex(new[] { "Email" }, "users_email_key")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("backend.Models.Favorite", b =>
                {
                    b.HasOne("backend.Models.User", "user")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_favorite_user");

                    b.Navigation("user");
                });

            modelBuilder.Entity("backend.Models.Hottel", b =>
                {
                    b.HasOne("backend.Models.User", "User")
                        .WithMany("Hottels")
                        .HasForeignKey("Created_By_UserId")
                        .HasConstraintName("fk_hotel_user");

                    b.HasOne("backend.Models.Tourist_Area", "Tourist_Area")
                        .WithMany("Hottels")
                        .HasForeignKey("Tourist_Area_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hotel_tourist_area");

                    b.Navigation("Tourist_Area");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.RefreshToken", b =>
                {
                    b.HasOne("backend.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.Review", b =>
                {
                    b.HasOne("backend.Models.User", "user")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_review_user");

                    b.Navigation("user");
                });

            modelBuilder.Entity("backend.Models.Tour", b =>
                {
                    b.HasOne("backend.Models.User", "User")
                        .WithMany("Tours")
                        .HasForeignKey("Created_By_UserId")
                        .HasConstraintName("fk_tour_user");

                    b.HasOne("backend.Models.Tourist_Area", null)
                        .WithMany("Tours")
                        .HasForeignKey("Tourist_AreaId");

                    b.HasOne("backend.Models.Tourist_Area", "Tourist_Area")
                        .WithMany()
                        .HasForeignKey("Tourist_Area_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tour_tourist_area");

                    b.Navigation("Tourist_Area");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.Tourist_Area", b =>
                {
                    b.HasOne("backend.Models.User", "User")
                        .WithMany("Tourist_Areas")
                        .HasForeignKey("Created_By_UserId")
                        .HasConstraintName("fk_tourist_area_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.Tourist_Area", b =>
                {
                    b.Navigation("Hottels");

                    b.Navigation("Tours");
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("Hottels");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Reviews");

                    b.Navigation("Tourist_Areas");

                    b.Navigation("Tours");
                });
#pragma warning restore 612, 618
        }
    }
}
