// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Models;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(CnpmContext))]
    [Migration("20260412111839_AddContactAddressToBooking")]
    partial class AddContactAddressToBooking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Advertisement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("End_date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("end_date")
                        .HasDefaultValueSql("now() + interval '31 days'");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("Position")
                        .HasColumnType("text")
                        .HasColumnName("position");

                    b.Property<string>("Size")
                        .HasColumnType("text")
                        .HasColumnName("size");

                    b.Property<DateTime?>("Start_date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("start_date")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("advertisements_pkey");

                    b.HasIndex("Position")
                        .HasDatabaseName("ix_advertisements_position");

                    b.HasIndex("IsActive", "Start_date", "End_date")
                        .HasDatabaseName("ix_advertisements_active_date");

                    b.ToTable("advertisements", (string)null);
                });

            modelBuilder.Entity("backend.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BookingStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pending")
                        .HasColumnName("booking_status");

                    b.Property<string>("BookingType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("booking_type");

                    b.Property<string>("ContactAddress")
                        .HasColumnType("text")
                        .HasColumnName("contact_address");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contact_name");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contact_phone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Unpaid")
                        .HasColumnName("payment_status");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("total_amount");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("bookings_pkey");

                    b.HasIndex("BookingStatus")
                        .HasDatabaseName("ix_bookings_status");

                    b.HasIndex("BookingType")
                        .HasDatabaseName("ix_bookings_type");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_bookings_user_id");

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("backend.Models.Booking_Detail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("integer")
                        .HasColumnName("booking_id");

                    b.Property<int?>("HotelRoomId")
                        .HasColumnType("integer")
                        .HasColumnName("hotel_room_id");

                    b.Property<bool>("IsPrivateTour")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_private_tour");

                    b.Property<string>("SeatNumber")
                        .HasColumnType("text")
                        .HasColumnName("seat_number");

                    b.Property<int?>("TourDepartureId")
                        .HasColumnType("integer")
                        .HasColumnName("tour_departure_id");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("booking_details_pkey");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("ix_booking_details_booking_id");

                    b.HasIndex("HotelRoomId")
                        .HasDatabaseName("ix_booking_details_hotel_room_id");

                    b.HasIndex("TourDepartureId")
                        .HasDatabaseName("ix_booking_details_tour_departure_id");

                    b.ToTable("booking_details", (string)null);
                });

            modelBuilder.Entity("backend.Models.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("EntityId")
                        .HasColumnType("integer")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .HasColumnType("text")
                        .HasColumnName("entity_type");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("favorites_pkey");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_favorites_user_id");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_favorites_entity");

                    b.HasIndex("UserId", "EntityType", "EntityId")
                        .HasDatabaseName("ix_favorites_user_entity");

                    b.ToTable("favorites", (string)null);
                });

            modelBuilder.Entity("backend.Models.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("New")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("feedbacks_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("feedbacks", (string)null);
                });

            modelBuilder.Entity("backend.Models.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<int>("ClickCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("click_count");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("Created_By_UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("FavoriteCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("favorite_count");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("numeric")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("numeric")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("NumberOfPeople")
                        .HasColumnType("integer")
                        .HasColumnName("number_of_people");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<decimal>("RatingAverage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(0m)
                        .HasColumnName("rating_average");

                    b.Property<int>("RatingCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("rating_count");

                    b.Property<int>("RatingTotal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("rating_total");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int>("Tourist_Place_Id")
                        .HasColumnType("integer")
                        .HasColumnName("tourist_place_id");

                    b.HasKey("Id")
                        .HasName("hottels_pkey");

                    b.HasIndex("ClickCount")
                        .HasDatabaseName("ix_hottels_click");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_hottels_created_at");

                    b.HasIndex("Created_By_UserId")
                        .HasDatabaseName("ix_hottels_created_by_user");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_hottels_name");

                    b.HasIndex("RatingAverage")
                        .HasDatabaseName("ix_hottels_rating");

                    b.HasIndex("Tourist_Place_Id")
                        .HasDatabaseName("ix_hottels_tourist_place_id");

                    b.HasIndex("RatingAverage", "ClickCount")
                        .HasDatabaseName("ix_hottels_popular");

                    b.ToTable("hottels", (string)null);
                });

            modelBuilder.Entity("backend.Models.Hotel_Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Floor")
                        .HasColumnType("integer")
                        .HasColumnName("floor");

                    b.Property<int>("HotelId")
                        .HasColumnType("integer")
                        .HasColumnName("hotel_id");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("room_name");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Standard")
                        .HasColumnName("room_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Available")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("hotel_rooms_pkey");

                    b.HasIndex("HotelId")
                        .HasDatabaseName("ix_hotel_rooms_hotel_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_hotel_rooms_status");

                    b.ToTable("hotel_rooms", (string)null);
                });

            modelBuilder.Entity("backend.Models.Img", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_type");

                    b.Property<bool>("IsCover")
                        .HasColumnType("boolean")
                        .HasColumnName("is_cover");

                    b.Property<string>("url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("imgs_pkey");

                    b.HasIndex("IsCover")
                        .HasDatabaseName("ix_imgs_cover");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_imgs_entity");

                    b.ToTable("imgs", (string)null);
                });

            modelBuilder.Entity("backend.Models.Marker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool?>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_public");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("numeric")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("numeric")
                        .HasColumnName("longitude");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int?>("TouristPlaceId")
                        .HasColumnType("integer")
                        .HasColumnName("tourist_place_id");

                    b.Property<int?>("Tourist_PlaceId")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("markers_pkey");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_markers_user");

                    b.HasIndex("TouristPlaceId")
                        .HasDatabaseName("ix_markers_touristPlace");

                    b.HasIndex("Tourist_PlaceId");

                    b.ToTable("markers", (string)null);
                });

            modelBuilder.Entity("backend.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool?>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_read");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("notifications_pkey");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_notifications_user");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("backend.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_revoked");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("refresh_tokens_pkey");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_refresh_tokens_expires_at");

                    b.HasIndex("TokenHash")
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("backend.Models.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("EntityId")
                        .HasColumnType("integer")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .HasColumnType("text")
                        .HasColumnName("entity_type");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<Guid?>("ReportedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("reported_by_user_id");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("reports_pkey");

                    b.HasIndex("ReportedByUserId")
                        .HasDatabaseName("ix_reports_user");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_reports_entity");

                    b.ToTable("reports", (string)null);
                });

            modelBuilder.Entity("backend.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("EntityId")
                        .HasColumnType("integer")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .HasColumnType("text")
                        .HasColumnName("entity_type");

                    b.Property<int>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("reviews_pkey");

                    b.HasIndex("Score")
                        .HasDatabaseName("ix_reviews_score");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_reviews_user_id");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_reviews_entity");

                    b.ToTable("reviews", (string)null);
                });

            modelBuilder.Entity("backend.Models.Tour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClickCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("click_count");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("Created_By_UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<decimal?>("DepartureLatitude")
                        .HasColumnType("decimal(18, 10)")
                        .HasColumnName("DepartureLatitude");

                    b.Property<string>("DepartureLocationName")
                        .HasColumnType("text")
                        .HasColumnName("DepartureLocationName");

                    b.Property<decimal?>("DepartureLongitude")
                        .HasColumnType("decimal(18, 10)")
                        .HasColumnName("DepartureLongitude");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("DurationDays")
                        .HasColumnType("integer")
                        .HasColumnName("duration_days");

                    b.Property<int>("FavoriteCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("favorite_count");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("NumberOfPeople")
                        .HasColumnType("integer")
                        .HasColumnName("number_of_people");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<decimal>("RatingAverage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(0m)
                        .HasColumnName("rating_average");

                    b.Property<int>("RatingCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("rating_count");

                    b.Property<int>("RatingTotal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("rating_total");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Available")
                        .HasColumnName("Status");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("TourType")
                        .HasColumnType("text")
                        .HasColumnName("TourType");

                    b.Property<int>("Tourist_Area_Id")
                        .HasColumnType("integer")
                        .HasColumnName("tourist_area_id");

                    b.Property<string>("Vehicle")
                        .HasColumnType("text")
                        .HasColumnName("Vehicle");

                    b.HasKey("Id")
                        .HasName("tour_id");

                    b.HasIndex("ClickCount")
                        .HasDatabaseName("ix_tours_click");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_tours_created_at");

                    b.HasIndex("Created_By_UserId")
                        .HasDatabaseName("ix_tours_created_by_user");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_tours_name");

                    b.HasIndex("RatingAverage")
                        .HasDatabaseName("ix_tours_rating");

                    b.HasIndex("Tourist_Area_Id")
                        .HasDatabaseName("ix_tours_tourist_area_id");

                    b.HasIndex("RatingAverage", "ClickCount")
                        .HasDatabaseName("ix_tours_popular");

                    b.ToTable("tours", (string)null);
                });

            modelBuilder.Entity("backend.Models.Tour_Departure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableSeats")
                        .HasColumnType("integer")
                        .HasColumnName("available_seats");

                    b.Property<string>("BookedSeats")
                        .HasColumnType("jsonb")
                        .HasColumnName("booked_seats");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Open")
                        .HasColumnName("status");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("integer")
                        .HasColumnName("total_seats");

                    b.Property<int>("TourId")
                        .HasColumnType("integer")
                        .HasColumnName("tour_id");

                    b.HasKey("Id")
                        .HasName("tour_departures_pkey");

                    b.HasIndex("StartDate")
                        .HasDatabaseName("ix_tour_departures_start_date");

                    b.HasIndex("TourId")
                        .HasDatabaseName("ix_tour_departures_tour_id");

                    b.ToTable("tour_departures", (string)null);
                });

            modelBuilder.Entity("backend.Models.Tour_Itinerary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("DayNumber")
                        .HasColumnType("integer")
                        .HasColumnName("day_number");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int>("TourId")
                        .HasColumnType("integer")
                        .HasColumnName("tour_id");

                    b.Property<int>("Tourist_Place_Id")
                        .HasColumnType("integer")
                        .HasColumnName("tourist_place_id");

                    b.HasKey("Id")
                        .HasName("tour_itineraries_pkey");

                    b.HasIndex("TourId")
                        .HasDatabaseName("ix_itinerary_tour");

                    b.HasIndex("Tourist_Place_Id")
                        .HasDatabaseName("ix_itinerary_place");

                    b.ToTable("tour_itineraries", (string)null);
                });

            modelBuilder.Entity("backend.Models.Tourist_Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<int>("ClickCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("click_count");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("Created_By_UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("FavoriteCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("favorite_count");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("numeric")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("numeric")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal>("RatingAverage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(0m)
                        .HasColumnName("rating_average");

                    b.Property<int>("RatingCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("rating_count");

                    b.Property<int>("RatingTotal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("rating_total");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Available")
                        .HasColumnName("Status");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("tourist_areas_pkey");

                    b.HasIndex("ClickCount")
                        .HasDatabaseName("ix_tourist_area_click");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_tourist_area_created_at");

                    b.HasIndex("Created_By_UserId")
                        .HasDatabaseName("ix_tourist_areas_created_by_user");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_tourist_areas_name");

                    b.HasIndex("RatingAverage")
                        .HasDatabaseName("ix_tourist_area_rating");

                    b.HasIndex("RatingAverage", "ClickCount")
                        .HasDatabaseName("ix_tourist_area_popular");

                    b.ToTable("tourist_areas", (string)null);
                });

            modelBuilder.Entity("backend.Models.Tourist_Place", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<int>("ClickCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("click_count");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("Created_By_UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("FavoriteCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("favorite_count");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("numeric")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("numeric")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal>("RatingAverage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(0m)
                        .HasColumnName("rating_average");

                    b.Property<int>("RatingCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("rating_count");

                    b.Property<int>("RatingTotal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("rating_total");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Available")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int>("Tourist_Area_Id")
                        .HasColumnType("integer")
                        .HasColumnName("tourist_area_id");

                    b.HasKey("Id")
                        .HasName("tourist_places_pkey");

                    b.HasIndex("Created_By_UserId")
                        .HasDatabaseName("ix_tourist_places_user");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_tourist_places_name");

                    b.HasIndex("RatingAverage")
                        .HasDatabaseName("ix_tourist_places_rating");

                    b.HasIndex("Tourist_Area_Id")
                        .HasDatabaseName("ix_tourist_places_area");

                    b.HasIndex("RatingAverage", "ClickCount")
                        .HasDatabaseName("ix_tourist_places_popular");

                    b.ToTable("tourist_places", (string)null);
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Avt")
                        .HasColumnType("text")
                        .HasColumnName("avt");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<DateTime?>("ResetPasswordExpiry")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("ResetPasswordExpiry")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ResetPasswordToken")
                        .HasColumnType("text")
                        .HasColumnName("ResetPasswordToken");

                    b.Property<string>("Role")
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Active")
                        .HasColumnName("Status");

                    b.Property<string>("User_Search_History")
                        .HasColumnType("text")
                        .HasColumnName("User_Search_History");

                    b.HasKey("Id")
                        .HasName("users_pkey");

                    b.HasIndex("Role")
                        .HasDatabaseName("ix_users_role");

                    b.HasIndex(new[] { "Email" }, "users_email_key")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("backend.Models.Booking", b =>
                {
                    b.HasOne("backend.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_booking_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.Booking_Detail", b =>
                {
                    b.HasOne("backend.Models.Booking", "Booking")
                        .WithMany("BookingDetails")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_booking_detail_booking");

                    b.HasOne("backend.Models.Hotel_Room", "HotelRoom")
                        .WithMany()
                        .HasForeignKey("HotelRoomId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_booking_detail_hotel_room");

                    b.HasOne("backend.Models.Tour_Departure", "TourDeparture")
                        .WithMany()
                        .HasForeignKey("TourDepartureId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_booking_detail_tour_departure");

                    b.Navigation("Booking");

                    b.Navigation("HotelRoom");

                    b.Navigation("TourDeparture");
                });

            modelBuilder.Entity("backend.Models.Favorite", b =>
                {
                    b.HasOne("backend.Models.User", "user")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_favorite_user");

                    b.Navigation("user");
                });

            modelBuilder.Entity("backend.Models.Feedback", b =>
                {
                    b.HasOne("backend.Models.User", "User")
                        .WithMany("Feedbacks")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_feedback_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.Hotel", b =>
                {
                    b.HasOne("backend.Models.User", "User")
                        .WithMany("Hottels")
                        .HasForeignKey("Created_By_UserId")
                        .HasConstraintName("fk_hotel_user");

                    b.HasOne("backend.Models.Tourist_Place", "Tourist_Place")
                        .WithMany("Hotels")
                        .HasForeignKey("Tourist_Place_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hotel_tourist_place");

                    b.Navigation("Tourist_Place");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.Hotel_Room", b =>
                {
                    b.HasOne("backend.Models.Hotel", "Hotel")
                        .WithMany("Rooms")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hotel_room");

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("backend.Models.Marker", b =>
                {
                    b.HasOne("backend.Models.User", "User")
                        .WithMany("Markers")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_marker_user");

                    b.HasOne("backend.Models.Tourist_Place", "Tourist_Place")
                        .WithMany()
                        .HasForeignKey("TouristPlaceId")
                        .HasConstraintName("FK_Markers_TouristPlace");

                    b.HasOne("backend.Models.Tourist_Place", null)
                        .WithMany("Markers")
                        .HasForeignKey("Tourist_PlaceId");

                    b.Navigation("Tourist_Place");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.Notification", b =>
                {
                    b.HasOne("backend.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_notification_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.RefreshToken", b =>
                {
                    b.HasOne("backend.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.Report", b =>
                {
                    b.HasOne("backend.Models.User", "User")
                        .WithMany("Reports")
                        .HasForeignKey("ReportedByUserId")
                        .HasConstraintName("fk_report_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.Review", b =>
                {
                    b.HasOne("backend.Models.User", "user")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_review_user");

                    b.Navigation("user");
                });

            modelBuilder.Entity("backend.Models.Tour", b =>
                {
                    b.HasOne("backend.Models.User", "User")
                        .WithMany("Tours")
                        .HasForeignKey("Created_By_UserId")
                        .HasConstraintName("fk_tour_user");

                    b.HasOne("backend.Models.Tourist_Area", "Tourist_Area")
                        .WithMany("Tours")
                        .HasForeignKey("Tourist_Area_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tour_tourist_area");

                    b.Navigation("Tourist_Area");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.Tour_Departure", b =>
                {
                    b.HasOne("backend.Models.Tour", "Tour")
                        .WithMany("Departures")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tour_departure");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("backend.Models.Tour_Itinerary", b =>
                {
                    b.HasOne("backend.Models.Tour", "Tour")
                        .WithMany("Tour_Itinerarys")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_itinerary_tour");

                    b.HasOne("backend.Models.Tourist_Place", "Tourist_Place")
                        .WithMany("Tour_Itineraries")
                        .HasForeignKey("Tourist_Place_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_itinerary_place");

                    b.Navigation("Tour");

                    b.Navigation("Tourist_Place");
                });

            modelBuilder.Entity("backend.Models.Tourist_Area", b =>
                {
                    b.HasOne("backend.Models.User", "User")
                        .WithMany("Tourist_Areas")
                        .HasForeignKey("Created_By_UserId")
                        .HasConstraintName("fk_tourist_area_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.Tourist_Place", b =>
                {
                    b.HasOne("backend.Models.User", "User")
                        .WithMany("Tourist_Place")
                        .HasForeignKey("Created_By_UserId")
                        .HasConstraintName("fk_tourist_place_user");

                    b.HasOne("backend.Models.Tourist_Area", "Tourist_Area")
                        .WithMany("Tourist_Places")
                        .HasForeignKey("Tourist_Area_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tourist_place_area");

                    b.Navigation("Tourist_Area");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.Booking", b =>
                {
                    b.Navigation("BookingDetails");
                });

            modelBuilder.Entity("backend.Models.Hotel", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("backend.Models.Tour", b =>
                {
                    b.Navigation("Departures");

                    b.Navigation("Tour_Itinerarys");
                });

            modelBuilder.Entity("backend.Models.Tourist_Area", b =>
                {
                    b.Navigation("Tourist_Places");

                    b.Navigation("Tours");
                });

            modelBuilder.Entity("backend.Models.Tourist_Place", b =>
                {
                    b.Navigation("Hotels");

                    b.Navigation("Markers");

                    b.Navigation("Tour_Itineraries");
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("Feedbacks");

                    b.Navigation("Hottels");

                    b.Navigation("Markers");

                    b.Navigation("Notifications");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Reports");

                    b.Navigation("Reviews");

                    b.Navigation("Tourist_Areas");

                    b.Navigation("Tourist_Place");

                    b.Navigation("Tours");
                });
#pragma warning restore 612, 618
        }
    }
}
